version: '3.8'

services:
  db:
    container_name: local_postgres
    hostname: postgres_hostname
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5433:5432'  # Map container port 5432 to host port 5433
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    container_name: local_redis
    hostname: redis_hostname
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  db:
  redis: