server:
  port: 4040

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:5433}/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: update
    database: postgresql
    show-sql: false
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_CONNECTION_HOST:localhost}
      port: ${REDIS_CONNECTION_PORT:6379}
